require 'block'

describe 'Block' do

  it 'maps the ids from the API to actual blocks' do

    Block.new(0).material.should eq(:air)
    Block.new(1).material.should eq(:stone)
    Block.new(2).material.should eq(:grass)
    Block.new(3).material.should eq(:dirt)
    Block.new(4).material.should eq(:cobblestone)
    Block.new(5).material.should eq(:wood_planks)
    Block.new(6).material.should eq(:sapling)
    Block.new(7).material.should eq(:bedrock)
    Block.new(8).material.should eq(:water_flowing)
    Block.new(9).material.should eq(:water_stationary)
    Block.new(10).material.should eq(:lava_flowing)
    Block.new(11).material.should eq(:laval_stationary)
    Block.new(12).material.should eq(:sand)
    Block.new(13).material.should eq(:gravel)
    Block.new(14).material.should eq(:gold_ore)
    Block.new(15).material.should eq(:iron_ore)
    Block.new(16).material.should eq(:coal_ore)
    Block.new(17).material.should eq(:wood)
    Block.new(18).material.should eq(:leaves)
    Block.new(20).material.should eq(:glass)
    Block.new(21).material.should eq(:lapis_lazuli_ore)
    Block.new(22).material.should eq(:lapis_lazuli_block)
    Block.new(24).material.should eq(:sandstone)
    Block.new(26).material.should eq(:bed)
    Block.new(30).material.should eq(:cobweb)
    Block.new(31).material.should eq(:grass_tall)
    Block.new(35).material.should eq(:wool)
    Block.new(37).material.should eq(:flower_yellow)
    Block.new(38).material.should eq(:flower_cyan)
    Block.new(39).material.should eq(:mushroom_brown)
    Block.new(40).material.should eq(:mushroom_red)
    Block.new(41).material.should eq(:gold_block)
    Block.new(42).material.should eq(:iron_block)
    Block.new(43).material.should eq(:stone_slab_double)
    Block.new(44).material.should eq(:stone_slab)
    Block.new(45).material.should eq(:brick_block)
    Block.new(46).material.should eq(:tnt)
    Block.new(47).material.should eq(:bookshelf)
    Block.new(48).material.should eq(:moss_stone)
    Block.new(49).material.should eq(:obsidian)
    Block.new(50).material.should eq(:torch)
    Block.new(51).material.should eq(:fire)
    Block.new(53).material.should eq(:stairs_wood)
    Block.new(54).material.should eq(:chest)
    Block.new(56).material.should eq(:diamond_ore)
    Block.new(57).material.should eq(:diamond_block)
    Block.new(58).material.should eq(:crafting_table)
    Block.new(60).material.should eq(:farmland)
    Block.new(61).material.should eq(:furnace_inactive)
    Block.new(62).material.should eq(:furnace_active)
    Block.new(64).material.should eq(:door_wood)
    Block.new(65).material.should eq(:ladder)
    Block.new(67).material.should eq(:stairs_cobblestone)
    Block.new(71).material.should eq(:door_iron)
    Block.new(73).material.should eq(:redstone_ore)
    Block.new(78).material.should eq(:snow)
    Block.new(79).material.should eq(:ice)
    Block.new(80).material.should eq(:snow_block)
    Block.new(81).material.should eq(:cactus)
    Block.new(82).material.should eq(:clay)
    Block.new(83).material.should eq(:sugar_cane)
    Block.new(85).material.should eq(:fence)
    Block.new(89).material.should eq(:glowstone_block)
    Block.new(95).material.should eq(:bedrock_invisible)
    Block.new(98).material.should eq(:stone_brick)
    Block.new(102).material.should eq(:glass_pane)
    Block.new(103).material.should eq(:melon)
    Block.new(107).material.should eq(:fence_gate)
    Block.new(246).material.should eq(:glowing_obsidian)
    Block.new(247).material.should eq(:nether_reactor_core)
  end

end
